### ISSUE TITLE
Updated from previous version I got `ValueType` error.

### ISSUE THREAD

**Issue by Bartmax** [RickStrahl/Westwind.Globalization#26]
On localizationAdmin I receive a `ValueType` error. Diggin into the xhr request the informations is as follows :

```
Remote Address:[::1]:56137
Request URL:http://localhost:56137/localizationAdmin/localizationService.ashx?method=GetResourceItems
Request Method:POST
Status Code:500 Internal Server Error

**Response Headers**
HTTP/1.1 500 Internal Server Error
Cache-Control: private
Content-Type: application/json
Server: Microsoft-IIS/10.0
X-AspNet-Version: 4.0.30319
X-SourceFiles: =?UTF-8?B?QzpcUmVwb3NcQmFydFxCaW9sb2dpYVRvdGFsXEJvdXJvblxzcmNcQXBwc1xCb3Vyb24uV2ViXGxvY2FsaXphdGlvbkFkbWluXGxvY2FsaXphdGlvblNlcnZpY2UuYXNoeA==?=
X-Powered-By: ASP.NET
Date: Mon, 25 May 2015 22:57:24 GMT
Content-Length: 815

**Request Headers**
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,es;q=0.6
Connection:keep-alive
Content-Length:97
Content-Type:application/json;charset=UTF-8
Cookie:__RequestVerificationToken=BTSTNtLyTInr5WppJhM8xsYDOjO3-LqXgj3sf5gEsMCFiDsyoMvAuwGcAQgcSk7WPpMLUMiJyFperyezB1i3pUrx6tjxOLS2bzqRQvwGn2A1; RE30feT1d9Q=CfDJ8AH5CUgCE_9Nq2falogucjcUay2l6-Kf3fjvTDcv5DyCq8SC5V5Ig4qRVlt2Xmv7lvMeDFiaGncqipxd6Hiyeiq0YPVTSQP1SHSfLxPQ0qETVq_EpIRm5c6EgQjLvO8asz9IxzRhOzs4BT8MOT9kJxk; .AspNet.ApplicationCookie=TGBtACaHnEjZ09u3f8eEuQSCG1SYRsmoxBpHDSL5YShasAIDyMgo58fdqb-FCBskm4DRj866Hih-IZTQ-UmbGINSnFuEPiCM25YbL6A3TfysiFR94hZGF6rTbPD1UWsRQaTM7XgjcmYYZ7QtRaVv1mof_Y2RKAlCR1Df4oa98uMVafkuwVQ9c7_3J88AQPXt4V-v7S9-hums15sBm69_CkyoA24fuQNZteIp48YGWUTC0Lfsp6bg4Dl03KYexsSxJShf2_VVJBVpZ8h8hMt6iFkUy6sFotNINq05ZRKRxiwX-KKW4ZLSIoxocJbTdH7iXDcZqGQneC1zarwBDsEfmg-1_fpry4DDxRiHp1VG9HP1B_Lnh05xUSs7gZCQUoLcRF7KlYMenxtVAMg-Xtz6O7O8iL8382TvGTEClkRU9kwgvXCfn3ifIweLOS7bxDWmWsdyYLZVYKmHp_IeI02t9preLte4E7XoBQzJ4UtK81I; _ga=GA1.1.730622452.1432540800; _gat=1
Host:localhost:56137
Origin:http://localhost:56137
Referer:http://localhost:56137/localizationAdmin/
User-Agent:Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.65 Safari/537.36

**Query String Parameters**
method=GetResourceItems

**Request Payload**
{"ResourceId":"Diccionario de enfermedades y sus conflictos asociados.","ResourceSet":"Products"}
```

```
data: null
detail: " at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
↵ at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
↵ at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
↵ at Westwind.Web.CallbackMethodProcessorHelper.ExecuteMethod(String method, Object target, String[] parameters, CallbackMethodParameterType paramType, CallbackMethodAttribute& callbackMethodAttribute)
↵ at Westwind.Web.JsonCallbackMethodProcessor.ProcessCallbackMethodCall(Object target, String methodToCall)"
isError: true
message: "ValueType"
resultData: null
source: null
statusCode: 500
```

**Comment by RickStrahl** [comment]
Yup that's a breaking change from the old version - add ValueType (int) with a default value of 0 to your localization table in the db.

**Comment by Bartmax** [comment]
Thanks! that worked.

Maybe it would be good to add it to your changelog, I was looking for changes in diff and changelog and couldn't find it.

**Comment by RickStrahl** [comment]
It's in the change log - it's in the v2.0-beta6 notes.

**Comment by Bartmax** [comment]
Oops, it's really big text there indeed! don't understand how I missed that one. sorry.
